### PR TITLE
Implement "ARPA" buttons (renamed Info Buttons)

### PR DESCRIPTION
**Pull request by maxatdetroit**
## Context

See context and various flavors of ARPA buttons to support in #100.

## This PR

* Create component for ARPA buttons; they're named 'Info Buttons' in the design system
* Create a story in storybook for the new component

Notes:
* Similar to #158, `body` is implemented as an attribute as opposed to slottable content. This is intentional to force users to keep the body brief and unformatted (since it's a button).
* Also similar to #158, I chose to write this component mostly using vanilla CSS, HTML, and bootstrap. See reasoning in [this comment](https://github.com/CityOfDetroit/COD-Design-System/pull/158#issuecomment-1944223897).

## Test

Storybook in Chromatic: https://65a994a97db54752e77a065c-keitbiqwdk.chromatic.com/?path=/docs/components-atoms-infobutton--docs

Sample:

image

### CODE REVIEW

**Comment by maxatdetroit** [comment]
Curious to get your thoughts @bankovic , @jedgar1mx : for the small form, I suggest we break the secondary title onto a new line.

**Comment by bankovic** [comment]
Let's talk about it on stand up... or earlier...
________________________________
From: Max Morgan ***@***.***>
Sent: Tuesday, February 13, 2024 4:59 PM
To: CityOfDetroit/COD-Design-System ***@***.***>
Cc: Goran Bankovic ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [CityOfDetroit/COD-Design-System] Implement "ARPA" buttons (renamed Info Buttons) (PR #160)


Curious to get your thoughts @bankovic<https://urldefense.com/v3/__https://github.com/bankovic__;!!NcXZSU8rfchoEksI!ZgaySWoz9IP_a5IiAzsZ-TEALSGfK6YnQ7N3EnyF9wyMG4fhv_JW2gVXkpdgghysXArt3mF0PcBOdfsJw4V3DAie7LPN4cw$> , @jedgar1mx<https://urldefense.com/v3/__https://github.com/jedgar1mx__;!!NcXZSU8rfchoEksI!ZgaySWoz9IP_a5IiAzsZ-TEALSGfK6YnQ7N3EnyF9wyMG4fhv_JW2gVXkpdgghysXArt3mF0PcBOdfsJw4V3DAieQlodh-4$> : for the small form, I suggest we break the secondary title onto a new line.

**Comment by maxatdetroit** [comment]
Moved this back to draft while I:
* Fix secondary title in place and force primary title to wrap
* Support forced multiline title

**Comment by maxatdetroit** [comment]
Added support for forced multiline and button will now wrap primary, secondary by default instead of wrapping the text within.

Ready for review.

**Review by jedgar1mx — CHANGES_REQUESTED** [review]
Current ARPA buttons used the full formatted body field. So it would probably be better to implement the body field as a `slot` similar to the `action-button` component.

**Comment by maxatdetroit** [comment]
@jedgar1mx this is updated to use slottable body section. Ready for review.

**Review by jedgar1mx — APPROVED** [review]

**Pull request merged**
