### PR TITLE
Create a video player component

### LINKED ISSUE #220: Create Video Player component
We need to create a video player component for the new legacy site. It should open a modal on click where the video can be played.

Image

### PR DESCRIPTION
**Pull request by maxatdetroit**
## Closes #220 

This PR introduces a video player component for the design system. Key features:
* Displays video thumbnail with play icon
  * Thumbnail supports inline (for future use cases) and full-width display modes (for legacy detroit site)
* Supports modal player
  * When clicked, modal opens (50% of viewport width on desktop and 90% on smaller devices) and plays the video within the modal
  * On modal close, the video stops playing
  * Note: Player has a display attribute so we can support inline (i.e. play the video where the thumbnail is) in the future without the modal. It's not implemented currently.
* Supports YouTube videos using the [YouTube iFrame Player API](https://developers.google.com/youtube/iframe_api_reference)
  * Note: `video-type` attribute is added so we can support other video types (vimeo, self-hosted) in the future and sensibly support backwards compatibility.

## Testing

See storybook in chromatic and click around. 

https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/b317ca92-524a-4d32-8946-ffb750f6f851

### CODE REVIEW

**Comment by maxatdetroit** [comment]
Moving to draft while I add some attributes for future implementation and fix layout on smaller viewports.

**Comment by jedgar1mx** [comment]
It looks like it's missing the back drop effect. It helps with focus but also for closing functionality.

image

**Comment by maxatdetroit** [comment]
Fixed @jedgar1mx . Anything else you think we could improve?

**Review by jedgar1mx — APPROVED** [review]
This looks good. Well done.

**Pull request merged**
